routes/admin.php
<?php 

Route::resource('series', 'SeriesController');
Route::resource('{series_by_id}/lessons', 'LessonsController');

routes/web.php
<?php

Auth::routes();
Route::get('/', 'FrontendController@welcome');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/profile/{user}', 'ProfilesController@index')->name('profile');
Route::get('/series/{series}', 'FrontendController@series')->name('series');
Route::get('/logout', function() { auth()->logout(); return redirect('/'); });
Route::get('/series', 'FrontendController@showAllseries')->name('all-series');
Route::get('register/confirm', 'ConfirmEmailController@index')->name('confirm-email');


Route::middleware('auth')->group(function() {
    Route::post('/card/update', 'ProfilesController@updateCard');
    Route::post('/subscribe', 'SubscriptionsController@subscribe');    
    Route::post('/subscription/change', 'SubscriptionsController@change')->name('subscriptions.change');        
    Route::get('/subscribe', 'SubscriptionsController@showSubscriptionForm');
    Route::post('/series/complete-lesson/{lesson}', 'WatchSeriesController@completeLesson');
    Route::get('/watch-series/{series}', 'WatchSeriesController@index')->name('series.learning');
    Route::get('/series/{series}/lesson/{lesson}', 'WatchSeriesController@showLesson')->name('series.watch');
});

app/Series.php
<?php

namespace Bahdcasts;

use Illuminate\Database\Eloquent\Model;

class Series extends Model
{
    /**
     * All database columns to be guarded from mass assignment
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * Eager load relationships
     *
     * @var array
     */
    protected $with = ['lessons'];

    /**
     * A series has many lessons
     *
     * @return void
     */
    public function lessons()
    {
    	return $this->hasMany(Lesson::class);
    }

    /**
     * Get the route key for the model.
     *
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'slug';
    }

    /**
     * Return the public path for series image
     *
     * @return string
     */
    public function getImagePathAttribute() {
        return asset('storage/' . $this->image_url);
    }

    /**
     * Get a list of lessons for series in watching order
     *
     * @return void
     */
    public function getOrderedLessons() {
        return $this->lessons()->orderBy('episode_number', 'asc')->get();
    }
}

resources/views/all-series.blade.php
@extends('layouts.app')

@section('header')
<header class="header header-inverse" style="background-color: #1ac28d">
  <div class="container text-center">

    <div class="row">
      <div class="col-12 col-lg-8 offset-lg-2">

        <h1>What do you wanna learn next ? !</h1>
      </div>
    </div>

  </div>
</header>
@stop

@section('content')
<section class="section" id="section-vtab">
    <div class="container">
        <header class="section-header">
        <h2>Here's all the fun stuff !</h2>
        </header>


        <div class="row gap-5">
            @forelse($series as $s)
                <div class="card mb-30">
                <div class="row">
                    <div class="col-12 col-md-4 align-self-center">
                    <a href=""><img src="{{ $s->image_path }}" alt="..."></a>
                    </div>

                    <div class="col-12 col-md-8">
                    <div class="card-block">
                        <h4 class="card-title">{{ $s->title }}</h4>
                    
                        <p class="card-text">{{ $s->description }}</p>
                        <a class="fw-600 fs-12" href="{{ route('series', $s->slug) }}">Read more <i class="fa fa-chevron-right fs-9 pl-8"></i></a>
                    </div>
                    </div>
                </div>
                </div>
            @empty
            @endforelse
        </div>


    </div>
</section>    
<section class="section bg-gray" id="section-vtab">
    <div class="container">
    </div>
</section>    

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/profile.blade.php
@extends('layouts.app')

@section('header')
<header class="header header-inverse" style="background-color: #1ac28d">
  <div class="container text-center">

    <div class="row">
      <div class="col-12 col-lg-8 offset-lg-2">

        <h1>Kati frantz</h1>
        <p class="fs-20 opacity-70">kati-frantz</p>
        <br>
        <h1>{{ $user->getTotalNumberOfCompletedLessons() }}</h1>
        <p class="fs-20 opacity-70">Lessons completed</p>
      </div>
    </div>

  </div>
</header>
@stop

@section('content')
<section class="section" id="section-vtab">
    <div class="container">
        <header class="section-header">
        <h2>Series being watched ...</h2>
        <hr>
        </header>


        <div class="row gap-5">
            @forelse($series as $s)
                <div class="card mb-30">
                <div class="row">
                    <div class="col-12 col-md-4 align-self-center">
                    <a href=""><img src="{{ $s->image_path }}" alt="..."></a>
                    </div>

                    <div class="col-12 col-md-8">
                    <div class="card-block">
                        <h4 class="card-title">{{ $s->title }}</h4>
                    
                        <p class="card-text">{{ $s->description }}</p>
                        <a class="fw-600 fs-12" href="{{ route('series', $s->slug) }}">Read more <i class="fa fa-chevron-right fs-9 pl-8"></i></a>
                    </div>
                    </div>
                </div>
                </div>
            @empty
            @endforelse

        </div>


    </div>
</section>    

@if(auth()->id() === $user->id)
@php 
$subscription = auth()->user()->subscriptions->first();
@endphp 
<section class="section bg-gray" id="section-vtab">
    <div class="container">
        <header class="section-header">
        <h2>Edit your profile</h2>
        <hr>
        </header>


        <div class="row gap-5">
        

        <div class="col-12 col-md-4">
            <ul class="nav nav-vertical">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#home-2">
                <h6>Personal details</h6>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#messages-2">
                <h6>Payments & Subscriptions</h6>
                </a>
            </li>
            @if(auth()->user()->card_brand)
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#settings-2">
                <h6>Card details</h6>
                </a>
            </li>
            @endif 
            </ul>
        </div>


        <div class="col-12 col-md-8 align-self-center">
            <div class="tab-content">
            
            <div class="tab-pane fade show active" id="home-2">
                <form action="{{ route('series.store')  }}" method="POST" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <input class="form-control form-control-lg" type="text" name="name" placeholder="Your name">
                        </div>
                        <div class="form-group">
                            <input class="form-control form-control-lg" type="text" name="email" placeholder="Your email">
                        </div>

                        <button class="btn btn-lg btn-primary btn-block" type="submit">Save changes</button>
                    </form>
            </div>

            <div class="tab-pane fade text-center" id="profile-2">
                
            </div>

            <div class="tab-pane fade" id="messages-2">
                <form action="{{ route('subscriptions.change') }}" method="post">
                    {{ csrf_field() }}
                    <h5 class="text-center">
                        Your current plan: 
                        @if($subscription)
                        <span class="badge badge-success">{{ $subscription->stripe_plan }}</span>
                        @else 
                        <span class="badge badge-danger">NO PLAN</span>
                        @endif 
                    </h5>
                    <br>
                    @if($subscription)
                    <select name="plan" class="form-control">
                        <option value="monthly">Monthly</option>
                        <option value="yearly">Yearly</option>
                    </select>
                    <br>
                    <p class="text-center">
                        <button class="btn btn-primary" type="submit">Change plan</button>
                    </p>
                    @endif
                    
                </form>
            </div>

            @if(auth()->user()->card_brand)
            <div class="tab-pane fade" id="settings-2">
                <div class="row">
                    <h2 class="text-center">
                        Your current card: <span class="badge badge-sm badge-primary">{{ auth()->user()->card_brand }}:{{ auth()->user()->card_last_four }}</span>
                    </h2>
                    <p class="ml-5 mt-5 text-center">
                        <vue-update-card email="{{ auth()->user()->email }}"></vue-update-card>
                    </p>
                </div>
            </div>
            @endif 

            </div>
        </div>


        </div>


    </div>
</section>
@endif

@endsection

@section('scripts')
    <script src="https://checkout.stripe.com/checkout.js"></script>
@endsection

resources/views/series.blade.php
@extends('layouts.app')

@section('header')
        <header class="header header-inverse h-fullscreen pb-80" style="background-image: url({{ $series->image_path }});" data-overlay="8">
            <div class="container text-center">

                <div class="row h-full">
                  <div class="col-12 col-lg-10 offset-lg-1 align-self-center">

                    <h1 class="display-4 hidden-sm-down">{{ $series->title }}</h1>
                    <h1 class="hidden-md-up">{{ $series->title }}</h1>
                    <br>
                    <br><br><br>
                    @auth
                      @hasStartedSeries($series)
                          <a href="{{ route('series.learning', $series->slug) }}" class="btn btn-lg btn-primary mr-16 btn-round">CONTINUE LEARNING</a>                        
                      @else
                          <a href="{{ route('series.learning', $series->slug) }}" class="btn btn-lg btn-primary mr-16 btn-round">START LEARNING</a>                      
                      @endhasStartedSeries
                    @else 
                          <a href="{{ route('series.learning', $series->slug) }}"  class="btn btn-lg btn-primary mr-16 btn-round">START LEARNING</a>                    
                    @endauth
                  </div>

                  <div class="col-12 align-self-end text-center">
                    <a class="scroll-down-1 scroll-down-inverse" href="#" data-scrollto="section-intro"><span></span></a>
                  </div>

                </div>

              </div>
        </header>
@endsection

@section('content')
    <section class="section">
      <div class="container">
        <header class="section-header">
          <small><strong>COURSE DESCRIPTION</strong></small>
          <h2>What's this course about ?</h2>
          <hr>
        </header>


        
        <div class="row gap-y">
          
          <div class="col-12 offset-md-2 col-md-8 mb-30">
            <p class="text-center">
              {{ $series->description }}
            </p>
          </div>
        </div>

      </div>
    </section>
    
    <section class="section bg-gray">
        <div class="container">
          <header class="section-header">
            <h2>Video Lessons</h2>
            <hr>
            <p class="lead">Sneak peek of the lessons already available in this course</p>
          </header>
        </div>
      </section>
@endsection

resources/views/subscribe.blade.php
@extends('layouts.app')

@section('header')
<header class="header header-inverse" style="background-color: #1ac28d">
  <div class="container text-center">

    <div class="row">
      <div class="col-12 col-lg-8 offset-lg-2">

        <h1>Subscribe to our awesome site</h1>
      </div>
    </div>

  </div>
</header>
@stop

@section('content')
<section class="section" id="section-vtab">
    <div class="container text-center">
        <vue-stripe email="{{ auth()->user()->email }}"></vue-stripe>
    </div>
</section>    

@endsection


@section('scripts')
    <script src="https://checkout.stripe.com/checkout.js"></script>
@endsection

resources/views/watch.blade.php
@extends('layouts.app')

@section('header')
<header class="header header-inverse" style="background-color: #9ac29d">
  <div class="container text-center">

    <div class="row">
      <div class="col-12 col-lg-8 offset-lg-2">

        <h1>{{ $lesson->title }}</h1>
        <p class="fs-20 opacity-70">{{  $series->title }}</p>

      </div>
    </div>

  </div>
</header>
@stop

@section('content')
  <div class="section bg-grey">
    <div class="container">
      @php
        $nextLesson = $lesson->getNextLesson();
        $prevLesson = $lesson->getPrevLesson();
      @endphp 
      <div class="row gap-y text-center"> 
        <div class="col-12">          
            <vue-player default_lesson="{{ $lesson }}" 
            @if($nextLesson->id !== $lesson->id)
                next_lesson_url="{{ route('series.watch', ['series' => $series->slug, 'lesson' => $nextLesson->id ]) }}"
            @endif 
            ></vue-player>
            @if($prevLesson->id !== $lesson->id)
              <a href="{{ route('series.watch', ['series' => $series->slug, 'lesson' => $prevLesson->id ]) }}" class="btn btn-info btn-lg pull-left">Prev Lesson</a>
            @endif
            @if($nextLesson->id !== $lesson->id)
              <a href="{{ route('series.watch', ['series' => $series->slug, 'lesson' => $nextLesson->id ]) }}" class="btn btn-info btn-lg pull-right">Next Lesson</a>
            @endif
            
        </div>
        <div class="col-12">
          <ul class="list-group">
            @foreach($series->getOrderedLessons() as $l)
              <li class="list-group-item
                @if($l->id == $lesson->id)
                  active
                @endif
                ">
                  @if(auth()->user()->hasCompletedLesson($l))
                    <b><small>COMPLETED</small></b>
                  @endif
                  <a href="{{ route('series.watch', ['series' => $series->slug, 'lesson' => $l->id]) }}">{{ $l->title }}</a>
              </li>
            @endforeach
          </ul>
        </div>
      </div>
    </div>
  </div>
@stop