routes/admin.php
<?php 

Route::resource('series', 'SeriesController');
Route::resource('{series_by_id}/lessons', 'LessonsController');

routes/web.php
<?php

Auth::routes();
Route::get('/', 'FrontendController@welcome');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/profile/{user}', 'ProfilesController@index')->name('profile');
Route::get('/series/{series}', 'FrontendController@series')->name('series');
Route::get('/logout', function() { auth()->logout(); return redirect('/'); });
Route::get('/series', 'FrontendController@showAllseries')->name('all-series');
Route::get('register/confirm', 'ConfirmEmailController@index')->name('confirm-email');


Route::middleware('auth')->group(function() {
    Route::post('/card/update', 'ProfilesController@updateCard');
    Route::post('/subscribe', 'SubscriptionsController@subscribe');    
    Route::post('/subscription/change', 'SubscriptionsController@change')->name('subscriptions.change');        
    Route::get('/subscribe', 'SubscriptionsController@showSubscriptionForm');
    Route::post('/series/complete-lesson/{lesson}', 'WatchSeriesController@completeLesson');
    Route::get('/watch-series/{series}', 'WatchSeriesController@index')->name('series.learning');
    Route::get('/series/{series}/lesson/{lesson}', 'WatchSeriesController@showLesson')->name('series.watch');
});

app/Http/Controllers/Admin/SeriesController.php
<?php

namespace Bahdcasts\Http\Controllers\Admin;

use Bahdcasts\Series;
use Illuminate\Http\Request;
use Bahdcasts\Http\Controllers\Controller;
use Bahdcasts\Http\Requests\CreateSeriesRequest;
use Bahdcasts\Http\Requests\UpdateSeriesRequest;

class SeriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.series.all')->withSeries(Series::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.series.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateSeriesRequest $request)
    {
        return $request->uploadSeriesImage()
                ->storeSeries();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Series $series)
    {
        return view('admin.series.index')
                ->withSeries($series);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Series $series)
    {
        return view('admin.series.edit')->withSeries($series);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateSeriesRequest $request, Series $series)
    {
        $request->updateSeries($series);

        session()->flash('success', 'Successfully updated series');
        return redirect()->route('series.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/series/all.blade.php
@extends('layouts.app')

@section('header')
<header class="header header-inverse" style="background-color: #c2b2cd;">
  <div class="container text-center">

    <div class="row">
      <div class="col-12 col-lg-8 offset-lg-2">

        <h1>All series</h1>
        <p class="fs-20 opacity-70">Let's make the world a better place for coders</p>

      </div>
    </div>

  </div>
</header>
@stop

@section('content')
  <div class="section bg-grey">
    <div class="container">

      <div class="row gap-y">
        <div class="col-12">          
            <table class="table">
                <thead>
                    <th>Title</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </thead>
                <tbody>
                    @forelse($series as $s)
                        <tr>
                            <td><a href="{{ route('series.show', $s->slug) }}">{{ $s->title }}</a></td>
                            <td>
                                <a href="{{ route('series.edit', $s->slug) }}" class="btn btn-info">Edit</a>
                            </td>
                            <td>
                                <a href="" class="btn btn-danger">Delete</a>
                            </td>
                        </tr>
                    @empty
                        <p class="text-center">No series yet</p>
                    @endforelse
                </tbody>
            </table>
        </div>
      </div>
    </div>
  </div>
@stop

resources/views/admin/series/create.blade.php
@extends('layouts.app')

@section('header')
<header class="header header-inverse" style="background-color: #c2b2cd;">
  <div class="container text-center">

    <div class="row">
      <div class="col-12 col-lg-8 offset-lg-2">

        <h1>Create a bahd series</h1>
        <p class="fs-20 opacity-70">Let's make the world a better place for coders</p>

      </div>
    </div>

  </div>
</header>
@stop

@section('content')
  <div class="section bg-grey">
    <div class="container">

      <div class="row gap-y">
        <div class="col-12">

          <form action="{{ route('series.store')  }}" method="POST" enctype="multipart/form-data">
            {{ csrf_field() }}
            <div class="form-group">
              <input class="form-control form-control-lg" type="text" name="title" placeholder="Your Series title">
            </div>

            <div class="form-group">
              <input class="form-control form-control-lg" type="file" name="image">
            </div>

            <div class="form-group">
              <textarea class="form-control form-control-lg" name="description" rows="4" placeholder="Your Description"></textarea>
            </div>


            <button class="btn btn-lg btn-primary btn-block" type="submit">Create series</button>
          </form>

        </div>
      </div>
    </div>
  </div>
@stop

resources/views/admin/series/edit.blade.php
@extends('layouts.app')

@section('header')
<header class="header header-inverse" style="background-color: #c2b2cd;">
  <div class="container text-center">

    <div class="row">
      <div class="col-12 col-lg-8 offset-lg-2">

        <h1>Edit: {{  $series->title }}</h1>
        <p class="fs-20 opacity-70">Let's make the world a better place for coders</p>

      </div>
    </div>

  </div>
</header>
@stop

@section('content')
  <div class="section bg-grey">
    <div class="container">

      <div class="row gap-y">
        <div class="col-12">

          <form action="{{ route('series.update', $series->slug)  }}" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}
            {{ method_field('PUT') }}
            <div class="form-group">
              <input class="form-control form-control-lg" type="text" value="{{ $series->title }}" name="title" placeholder="Your Series title">
            </div>

            <div class="form-group">
              <input class="form-control form-control-lg" type="file" name="image">
            </div>

            <div class="form-group">
              <textarea class="form-control form-control-lg" name="description" rows="4" placeholder="Your Description">{{ $series->description }}</textarea>
            </div>


            <button class="btn btn-lg btn-primary btn-block" type="submit">Update series</button>
          </form>

        </div>
      </div>
    </div>
  </div>
@stop

resources/views/admin/series/index.blade.php
@extends('layouts.app')

@section('header')
<header class="header header-inverse" style="background-color: #a18cd1;">
  <div class="container text-center">

    <div class="row">
      <div class="col-12 col-lg-8 offset-lg-2">

        <h1>{{ $series->title }}</h1>
        <p class="fs-20 opacity-70">Customize your series lessons</p>

      </div>
    </div>

  </div>
</header>
@stop

@section('content')
  <div class="section section-inverse">
    <div class="container">

      <div class="row gap-y">
        <div class="col-12">
          <vue-lessons default_lessons="{{ $series->lessons }}" series_id="{{ $series->id }}"></vue-lessons>
        </div>
      </div>
    </div>
  </div>
@stop